### ISSUE TITLE
Song Names Are Shown Incorrectly on macOS

### ISSUE THREAD

**Issue by vapronva** [amethyst-px/amethyst#11]
*at least on macOS; haven't tested on other OS, [unfortunately](https://thats-a-nice-argument-unfortunately.com)

## Description

When opening a folder (or any other file) the song name in the queue list is displaying the full path to that file on the computer, however the intended behaviour is, as far as I understand, to display filenames (with a file extension).

## Screenshots

| ![Screenshot of the Amethyst app (v1.1.9) on macOS](https://user-images.githubusercontent.com/35921969/169718579-85f4536b-b5f6-4812-b54e-a5756aa4213b.png) | 
|:--:| 
| *The audio file clearly has metadata tags and Amethyst shows them correctly, however the songs on the left-side bar are displaying full path to the file instead of a filename or "artist + title" name* |

## Other Information

- App Version: v1.1.9 (as of `df0711e` commit) built for `arm64`
- Environment: macOS 12.3

**Comment by Geoxor** [comment]
thats because linux/mac have paths written with forward slashes `/` instead of backward ones `\` it should be an easy fix
