### ISSUE TITLE
Shuffling problem

### ISSUE THREAD

**Issue by MrEnder0** [amethyst-px/amethyst#15]
when shuffling your list of songs while playing a song it shuffles but shows you are playing the song at the same index so if the song you were listening was the 5th one and you shuffle it shows you are playing whatever gets put as the 5th one even though its not.

**Comment by henry-lang** [comment]
Is this still an issue? Like do you mean the index should be a random one every time you click the shuffle button?

**Comment by MrEnder0** [comment]
What I mean is you select a song then shuffle it still plays the song it was playing like it should, but it shows on the left side it is playing a different song that's in the same position in the que as the song you are listening to before you shuffled. Hope this helps to explain what I mean.

**Comment by MrEnder0** [comment]
It seems the problem is fixed by it just stoping your old song and playing the new one that's at the index.
